scene_path: '/home/yons/8TB/data/data/renderData.npz'
cnn_path: '/home/yons/8TB/data/data/cnn.pth'
height: 720
width: 1280
focal: 750
max_tracing_tile: 30
reflection_scale: 2
origin: [0,10,0]
tensorRT: True 